import { Category, Professional, Profile, ServiceRequest, Quote, Message, Notification, Company } from '../types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-climatizacao',
    name: 'Climatização',
    slug: 'climatizacao',
    description: 'Instalação, limpeza e manutenção de ar-condicionado',
    icon: 'snowflake',
    is_active: true,
  },
  {
    id: 'cat-eletrica',
    name: 'Elétrica',
    slug: 'eletrica',
    description: 'Instalações elétricas, fiações, disjuntores e chuveiros',
    icon: 'zap',
    is_active: true,
  },
  {
    id: 'cat-hidraulica',
    name: 'Hidráulica',
    slug: 'hidraulica',
    description: 'Desentupimentos, torneiras, caixas d’água e encanamento',
    icon: 'droplet',
    is_active: true,
  },
  {
    id: 'cat-limpeza',
    name: 'Limpeza',
    slug: 'limpeza',
    description: 'Faxina residencial, pós-obra e higienização de estofados',
    icon: 'sparkles',
    is_active: true,
  },
  {
    id: 'cat-construcao',
    name: 'Construção',
    slug: 'construcao',
    description: 'Pedreiro, reformas, pisos, azulejos e reboco',
    icon: 'hard-hat',
    is_active: true,
  },
  {
    id: 'cat-pintura',
    name: 'Pintura',
    slug: 'pintura',
    description: 'Pintura de paredes, texturas, portões e acabamentos',
    icon: 'paint-roller',
    is_active: true,
  },
  {
    id: 'cat-automotivo',
    name: 'Automotivo',
    slug: 'automotivo',
    description: 'Socorro mecânico, bateria, freios e ar automotivo',
    icon: 'wrench',
    is_active: true,
  },
  {
    id: 'cat-tecnologia',
    name: 'Tecnologia',
    slug: 'tecnologia',
    description: 'Conserto de computadores, celulares, redes e Wi-Fi',
    icon: 'laptop',
    is_active: true,
  },
  {
    id: 'cat-montagem',
    name: 'Montagem',
    slug: 'montagem',
    description: 'Montagem e desmontagem de móveis e estantes',
    icon: 'tool',
    is_active: true,
  },
  {
    id: 'cat-outros',
    name: 'Outros',
    slug: 'outros',
    description: 'Chaveiro, carretos rápidos, jardinagem e reparos gerais',
    icon: 'grid',
    is_active: true,
  },
];

// Imperatriz - MA Coordinates (~ -5.5266, -47.4797)
export const IMPERATRIZ_CENTER = {
  lat: -5.5266,
  lng: -47.4797,
  name: 'Imperatriz - MA e região',
};

export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'prof-lucas',
    user_id: 'usr-lucas',
    full_name: 'Lucas Ferreira',
    email: 'lucas@exemplo.com',
    phone: '(99) 98452-1100',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'CLIENTE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'prof-joao',
    user_id: 'usr-joao',
    full_name: 'João Silva',
    email: 'joao.silva@quemresolve.com',
    phone: '(99) 99123-4567',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'PROFISSIONAL',
    created_at: new Date().toISOString(),
  },
  {
    id: 'prof-marcos',
    user_id: 'usr-marcos',
    full_name: 'Marcos Eletricista',
    email: 'marcos@quemresolve.com',
    phone: '(99) 98844-3322',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    role: 'PROFISSIONAL',
    created_at: new Date().toISOString(),
  },
  {
    id: 'prof-carlos',
    user_id: 'usr-carlos',
    full_name: 'Carlos Mendes',
    email: 'carlos.hidraulica@quemresolve.com',
    phone: '(99) 98111-2233',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    role: 'PROFISSIONAL',
    created_at: new Date().toISOString(),
  },
  {
    id: 'prof-empresa',
    user_id: 'usr-empresa',
    full_name: 'Roberto Diniz',
    email: 'contato@climatechsolucoes.com',
    phone: '(99) 3524-8899',
    avatar_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    role: 'EMPRESA',
    created_at: new Date().toISOString(),
  },
  {
    id: 'prof-admin',
    user_id: 'usr-admin',
    full_name: 'Administrador Quem Resolve',
    email: 'admin@quemresolve.com',
    phone: '(99) 99999-0000',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    role: 'ADMIN',
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_COMPANIES: Company[] = [
  {
    id: 'comp-climatech',
    owner_profile_id: 'prof-empresa',
    name: 'ClimaTech Soluções e Engenharia Térmica',
    description: 'Empresa especializada em sistemas centrais, splits e climatização comercial e residencial em Imperatriz.',
    logo_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=150&auto=format&fit=crop&q=80',
    phone: '(99) 3524-8899',
    email: 'contato@climatechsolucoes.com',
    address: 'Av. Dorgival Pinheiro de Sousa, 1420 - Centro, Imperatriz - MA',
    latitude: -5.5280,
    longitude: -47.4815,
    verification_status: 'verified',
    rating: 4.95,
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_PROFESSIONALS: Professional[] = [
  {
    id: 'pro-joao',
    profile_id: 'prof-joao',
    bio: 'Técnico em refrigeração com mais de 8 anos de experiência comprovada. Atendemos residências, comércios e empresas com pontualidade, higiene e garantia do serviço.',
    document_status: 'approved',
    verification_status: 'verified',
    rating: 4.9,
    total_reviews: 320,
    total_services: 342,
    is_available: true,
    latitude: -5.5245,
    longitude: -47.4760,
    service_radius_km: 20,
    specialties: ['Instalação', 'Manutenção', 'Limpeza', 'Refrigeração', 'Carga de Gás'],
    hourly_rate: 120,
    created_at: new Date().toISOString(),
  },
  {
    id: 'pro-marcos',
    profile_id: 'prof-marcos',
    bio: 'Eletricista credenciado pelo Senai. Troca de fiação, instalação de padrão Cemar/Equatorial, chuveiros, luminárias e painéis solares.',
    document_status: 'approved',
    verification_status: 'verified',
    rating: 4.85,
    total_reviews: 194,
    total_services: 215,
    is_available: true,
    latitude: -5.5310,
    longitude: -47.4840,
    service_radius_km: 18,
    specialties: ['Quadros de Luz', 'Chuveiros', 'Tomadas', 'Luminárias', 'Curto-circuito'],
    hourly_rate: 110,
    created_at: new Date().toISOString(),
  },
  {
    id: 'pro-carlos',
    profile_id: 'prof-carlos',
    bio: 'Encanador profissional com atendimento rápido para vazamentos, desentupimentos de pias e ralos e instalação de louças sanitárias.',
    document_status: 'approved',
    verification_status: 'verified',
    rating: 4.92,
    total_reviews: 210,
    total_services: 238,
    is_available: true,
    latitude: -5.5220,
    longitude: -47.4820,
    service_radius_km: 15,
    specialties: ['Vazamentos', 'Desentupimento', 'Caixas d’água', 'Válvulas Hydra'],
    hourly_rate: 100,
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_REQUESTS: ServiceRequest[] = [
  {
    id: 'req-ar-joao',
    client_id: 'prof-lucas',
    category_id: 'cat-climatizacao',
    title: 'Instalação e manutenção de ar-condicionado',
    description: 'Trabalhamos com instalação, manutenção e limpeza de ar-condicionado residencial e comercial. Qualidade e garantia no serviço.',
    status: 'professional_on_way',
    scheduled_date: new Date().toISOString().split('T')[0],
    scheduled_start: '10:30',
    scheduled_end: '12:00',
    address: 'Rua Ceará, 450 - Juçara, Imperatriz - MA',
    latitude: -5.5266,
    longitude: -47.4797,
    urgency: 'urgent',
    images: [
      {
        id: 'img-1',
        service_request_id: 'req-ar-joao',
        storage_path: 'service-images/ar-condicionado-1.jpg',
        public_url: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&auto=format&fit=crop&q=80',
        created_at: new Date().toISOString(),
      },
    ],
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'req-eletrica-1',
    client_id: 'prof-lucas',
    category_id: 'cat-eletrica',
    title: 'Troca de fiação e disjuntores do quadro geral',
    description: 'Disjuntor principal caindo ao ligar ar condicionado e chuveiro ao mesmo tempo.',
    status: 'quotes_received',
    scheduled_date: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    scheduled_start: '14:00',
    scheduled_end: '16:00',
    address: 'Av. Bernardo Sayão, 890 - Nova Imperatriz, Imperatriz - MA',
    latitude: -5.5210,
    longitude: -47.4720,
    urgency: 'normal',
    created_at: new Date(Date.now() - 7200000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_QUOTES: Quote[] = [
  {
    id: 'quote-1',
    service_request_id: 'req-ar-joao',
    professional_id: 'pro-joao',
    amount: 180.0,
    description: 'Higienização completa da unidade interna e externa + verificação do gás refrigerante com garantia de 90 dias.',
    estimated_duration: '1h 30min',
    available_date: new Date().toISOString().split('T')[0],
    available_time: '10:30',
    status: 'accepted',
    created_at: new Date(Date.now() - 2500000).toISOString(),
  },
  {
    id: 'quote-2',
    service_request_id: 'req-eletrica-1',
    professional_id: 'pro-marcos',
    amount: 220.0,
    description: 'Substituição do barramento, disjuntor bipolar 40A e balanceamento de fases.',
    estimated_duration: '2h',
    available_date: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    available_time: '14:00',
    status: 'pending',
    created_at: new Date(Date.now() - 1800000).toISOString(),
  },
];

export const INITIAL_MESSAGES: Message[] = [
  {
    id: 'msg-1',
    conversation_id: 'conv-ar-joao',
    sender_id: 'prof-lucas',
    message: 'Olá João! O ar condicionado é um Split 12.000 BTUs no segundo andar.',
    message_type: 'text',
    read_at: new Date(Date.now() - 1500000).toISOString(),
    created_at: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'msg-2',
    conversation_id: 'conv-ar-joao',
    sender_id: 'prof-joao',
    message: 'Perfeito, Lucas! Estou a caminho com a escada e o kit completo de higienização. Chego em 12 minutos!',
    message_type: 'text',
    read_at: new Date(Date.now() - 600000).toISOString(),
    created_at: new Date(Date.now() - 900000).toISOString(),
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    user_id: 'prof-lucas',
    title: 'João está a caminho!',
    message: 'Chegada estimada em 12 minutos no seu endereço em Imperatriz - MA.',
    type: 'pro_on_way',
    read_at: undefined,
    created_at: new Date(Date.now() - 600000).toISOString(),
  },
  {
    id: 'notif-2',
    user_id: 'prof-lucas',
    title: 'Novo orçamento recebido',
    message: 'Marcos Eletricista enviou um orçamento de R$ 220 para Troca de fiação.',
    type: 'new_quote',
    read_at: undefined,
    created_at: new Date(Date.now() - 1800000).toISOString(),
  },
];
